/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CollectionList : The list of collections that exist in the project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionList {
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<models::CollectionModel>>,
}

impl CollectionList {
    /// The list of collections that exist in the project.
    pub fn new() -> CollectionList {
        CollectionList {
            collections: None,
        }
    }
}

