/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureIndexRequestSpec {
    #[serde(rename = "pod")]
    pub pod: Box<models::ConfigureIndexRequestSpecPod>,
}

impl ConfigureIndexRequestSpec {
    pub fn new(pod: models::ConfigureIndexRequestSpecPod) -> ConfigureIndexRequestSpec {
        ConfigureIndexRequestSpec {
            pod: Box::new(pod),
        }
    }
}

