/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateIndexRequestSpec : The spec object defines how the index should be deployed.  For serverless indexes, you define only the cloud and region where the index should be hosted. For pod-based indexes, you define the environment where the index should be hosted, the pod type and size to use, and other index characteristics.  Serverless indexes are in public preview and are available only on AWS in the us-west-2 and us-east-1 regions. Test thoroughly before using serverless indexes in production. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexRequestSpec {
    #[serde(rename = "serverless", skip_serializing_if = "Option::is_none")]
    pub serverless: Option<Box<models::ServerlessSpec>>,
    #[serde(rename = "pod", skip_serializing_if = "Option::is_none")]
    pub pod: Option<Box<models::PodSpec>>,
}

impl CreateIndexRequestSpec {
    /// The spec object defines how the index should be deployed.  For serverless indexes, you define only the cloud and region where the index should be hosted. For pod-based indexes, you define the environment where the index should be hosted, the pod type and size to use, and other index characteristics.  Serverless indexes are in public preview and are available only on AWS in the us-west-2 and us-east-1 regions. Test thoroughly before using serverless indexes in production. 
    pub fn new() -> CreateIndexRequestSpec {
        CreateIndexRequestSpec {
            serverless: None,
            pod: None,
        }
    }
}

