/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmbedRequestParameters : Model-specific parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbedRequestParameters {
    /// Common property used to distinguish between types of data.
    #[serde(rename = "input_type", skip_serializing_if = "Option::is_none")]
    pub input_type: Option<String>,
    /// How to handle inputs longer than those supported by the model. If NONE, when the input exceeds the maximum input token length an error will be returned.
    #[serde(rename = "truncate", skip_serializing_if = "Option::is_none")]
    pub truncate: Option<String>,
}

impl EmbedRequestParameters {
    /// Model-specific parameters.
    pub fn new() -> EmbedRequestParameters {
        EmbedRequestParameters {
            input_type: None,
            truncate: None,
        }
    }
}

