[package]
name = "pinecone_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapi = { path = "../openapi" }
tokio = { version = "1", features = ["full"] }
mockito = "0.30"
regex = "1.10.4"
serde_json = "1.0.117"
serial_test = "3.1.1"
