/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// BackupModel : The BackupModel describes the configuration and status of a Pinecone backup.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupModel {
    /// Unique identifier for the backup.
    #[serde(rename = "backup_id")]
    pub backup_id: String,
    /// Name of the index from which the backup was taken.
    #[serde(rename = "source_index_name")]
    pub source_index_name: String,
    /// ID of the index.
    #[serde(rename = "source_index_id")]
    pub source_index_id: String,
    /// Optional user-defined name for the backup.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Optional description providing context for the backup.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Current status of the backup (e.g., Initializing, Ready, Failed).
    #[serde(rename = "status")]
    pub status: String,
    /// Cloud provider where the backup is stored.
    #[serde(rename = "cloud")]
    pub cloud: String,
    /// Cloud region where the backup is stored.
    #[serde(rename = "region")]
    pub region: String,
    /// The dimensions of the vectors to be inserted in the index.
    #[serde(rename = "dimension", skip_serializing_if = "Option::is_none")]
    pub dimension: Option<i32>,
    /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the `vector_type` is `dense`, the metric defaults to 'cosine'.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<Metric>,
    /// Total number of records in the backup.
    #[serde(rename = "record_count", skip_serializing_if = "Option::is_none")]
    pub record_count: Option<i32>,
    /// Number of namespaces in the backup.
    #[serde(rename = "namespace_count", skip_serializing_if = "Option::is_none")]
    pub namespace_count: Option<i32>,
    /// Size of the backup in bytes.
    #[serde(rename = "size_bytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i32>,
    /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '_', or '-'.  Values must be alphanumeric, ';', '@', '_', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
    /// Timestamp when the backup was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl BackupModel {
    /// The BackupModel describes the configuration and status of a Pinecone backup.
    pub fn new(
        backup_id: String,
        source_index_name: String,
        source_index_id: String,
        status: String,
        cloud: String,
        region: String,
    ) -> BackupModel {
        BackupModel {
            backup_id,
            source_index_name,
            source_index_id,
            name: None,
            description: None,
            status,
            cloud,
            region,
            dimension: None,
            metric: None,
            record_count: None,
            namespace_count: None,
            size_bytes: None,
            tags: None,
            created_at: None,
        }
    }
}
/// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If the 'vector_type' is 'sparse', the metric must be 'dotproduct'. If the `vector_type` is `dense`, the metric defaults to 'cosine'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Metric {
    #[serde(rename = "cosine")]
    Cosine,
    #[serde(rename = "euclidean")]
    Euclidean,
    #[serde(rename = "dotproduct")]
    Dotproduct,
}

impl Default for Metric {
    fn default() -> Metric {
        Self::Cosine
    }
}
