/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// BackupList : The list of backups that exist in the project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackupList {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::BackupModel>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::PaginationResponse>>,
}

impl BackupList {
    /// The list of backups that exist in the project.
    pub fn new() -> BackupList {
        BackupList {
            data: None,
            pagination: None,
        }
    }
}
