/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// ByocSpec : Configuration needed to deploy an index in a BYOC environment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ByocSpec {
    /// The environment where the index is hosted.
    #[serde(rename = "environment")]
    pub environment: String,
}

impl ByocSpec {
    /// Configuration needed to deploy an index in a BYOC environment.
    pub fn new(environment: String) -> ByocSpec {
        ByocSpec { environment }
    }
}
