/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// ConfigureIndexRequestEmbed : Configure the integrated inference embedding settings for this index.  You can convert an existing index to an integrated index by specifying the embedding model and field_map. The index vector type and dimension must match the model vector type and dimension, and the index similarity metric must be supported by the model. Refer to the [model guide](https://docs.pinecone.io/guides/inference/understanding-inference#embedding-models) for available models and model details.  You can later change the embedding configuration to update the field map, read parameters, or write parameters. Once set, the model cannot be changed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureIndexRequestEmbed {
    /// The name of the embedding model to use with the index. The index dimension and model dimension must match, and the index similarity metric must be supported by the model. The index embedding model cannot be changed once set.
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Identifies the name of the text field from your document model that will be embedded.
    #[serde(rename = "field_map", skip_serializing_if = "Option::is_none")]
    pub field_map: Option<serde_json::Value>,
    /// The read parameters for the embedding model.
    #[serde(rename = "read_parameters", skip_serializing_if = "Option::is_none")]
    pub read_parameters: Option<serde_json::Value>,
    /// The write parameters for the embedding model.
    #[serde(rename = "write_parameters", skip_serializing_if = "Option::is_none")]
    pub write_parameters: Option<serde_json::Value>,
}

impl ConfigureIndexRequestEmbed {
    /// Configure the integrated inference embedding settings for this index.  You can convert an existing index to an integrated index by specifying the embedding model and field_map. The index vector type and dimension must match the model vector type and dimension, and the index similarity metric must be supported by the model. Refer to the [model guide](https://docs.pinecone.io/guides/inference/understanding-inference#embedding-models) for available models and model details.  You can later change the embedding configuration to update the field map, read parameters, or write parameters. Once set, the model cannot be changed.
    pub fn new() -> ConfigureIndexRequestEmbed {
        ConfigureIndexRequestEmbed {
            model: None,
            field_map: None,
            read_parameters: None,
            write_parameters: None,
        }
    }
}
