/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// CreateIndexFromBackupRequest : The configuration needed to create a Pinecone index from a backup.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexFromBackupRequest {
    /// The name of the index. Resource name must be 1-45 characters long, start and end with an alphanumeric character, and consist only of lower case alphanumeric characters or '-'.
    #[serde(rename = "name")]
    pub name: String,
    /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '_', or '-'.  Values must be alphanumeric, ';', '@', '_', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
    #[serde(
        rename = "deletion_protection",
        skip_serializing_if = "Option::is_none"
    )]
    pub deletion_protection: Option<models::DeletionProtection>,
}

impl CreateIndexFromBackupRequest {
    /// The configuration needed to create a Pinecone index from a backup.
    pub fn new(name: String) -> CreateIndexFromBackupRequest {
        CreateIndexFromBackupRequest {
            name,
            tags: None,
            deletion_protection: None,
        }
    }
}
