/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// CreateIndexForModelRequestEmbed : Specify the integrated inference embedding configuration for the index.  Once set the model cannot be changed, but you can later update the embedding configuration for an integrated inference index including field map, read parameters, or write parameters.  Refer to the [model guide](https://docs.pinecone.io/guides/inference/understanding-inference#embedding-models) for available models and model details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexForModelRequestEmbed {
    /// The name of the embedding model to use for the index.
    #[serde(rename = "model")]
    pub model: String,
    /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If not specified, the metric will be defaulted according to the model. Cannot be updated once set.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<Metric>,
    /// Identifies the name of the text field from your document model that will be embedded.
    #[serde(rename = "field_map")]
    pub field_map: serde_json::Value,
    /// The dimension of embedding vectors produced for the index.
    #[serde(rename = "dimension", skip_serializing_if = "Option::is_none")]
    pub dimension: Option<i32>,
    /// The read parameters for the embedding model.
    #[serde(rename = "read_parameters", skip_serializing_if = "Option::is_none")]
    pub read_parameters: Option<serde_json::Value>,
    /// The write parameters for the embedding model.
    #[serde(rename = "write_parameters", skip_serializing_if = "Option::is_none")]
    pub write_parameters: Option<serde_json::Value>,
}

impl CreateIndexForModelRequestEmbed {
    /// Specify the integrated inference embedding configuration for the index.  Once set the model cannot be changed, but you can later update the embedding configuration for an integrated inference index including field map, read parameters, or write parameters.  Refer to the [model guide](https://docs.pinecone.io/guides/inference/understanding-inference#embedding-models) for available models and model details.
    pub fn new(model: String, field_map: serde_json::Value) -> CreateIndexForModelRequestEmbed {
        CreateIndexForModelRequestEmbed {
            model,
            metric: None,
            field_map,
            dimension: None,
            read_parameters: None,
            write_parameters: None,
        }
    }
}
/// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If not specified, the metric will be defaulted according to the model. Cannot be updated once set.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Metric {
    #[serde(rename = "cosine")]
    Cosine,
    #[serde(rename = "euclidean")]
    Euclidean,
    #[serde(rename = "dotproduct")]
    Dotproduct,
}

impl Default for Metric {
    fn default() -> Metric {
        Self::Cosine
    }
}
