/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// CreateIndexForModelRequest : The desired configuration for the index and associated embedding model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexForModelRequest {
    /// The name of the index. Resource name must be 1-45 characters long, start and end with an alphanumeric character, and consist only of lower case alphanumeric characters or '-'.
    #[serde(rename = "name")]
    pub name: String,
    /// The public cloud where you would like your index hosted.
    #[serde(rename = "cloud")]
    pub cloud: Cloud,
    /// The region where you would like your index to be created.
    #[serde(rename = "region")]
    pub region: String,
    #[serde(
        rename = "deletion_protection",
        skip_serializing_if = "Option::is_none"
    )]
    pub deletion_protection: Option<models::DeletionProtection>,
    /// Custom user tags added to an index. Keys must be 80 characters or less. Values must be 120 characters or less. Keys must be alphanumeric, '_', or '-'.  Values must be alphanumeric, ';', '@', '_', '-', '.', '+', or ' '. To unset a key, set the value to be an empty string.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "embed")]
    pub embed: Box<models::CreateIndexForModelRequestEmbed>,
}

impl CreateIndexForModelRequest {
    /// The desired configuration for the index and associated embedding model.
    pub fn new(
        name: String,
        cloud: Cloud,
        region: String,
        embed: models::CreateIndexForModelRequestEmbed,
    ) -> CreateIndexForModelRequest {
        CreateIndexForModelRequest {
            name,
            cloud,
            region,
            deletion_protection: None,
            tags: None,
            embed: Box::new(embed),
        }
    }
}
/// The public cloud where you would like your index hosted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cloud {
    #[serde(rename = "gcp")]
    Gcp,
    #[serde(rename = "aws")]
    Aws,
    #[serde(rename = "azure")]
    Azure,
}

impl Default for Cloud {
    fn default() -> Cloud {
        Self::Gcp
    }
}
