/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: unstable
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// DedicatedSpec : Configuration needed to deploy a dedicated environment index.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DedicatedSpec {
    /// The environment where the index is hosted.
    #[serde(rename = "environment")]
    pub environment: String,
}

impl DedicatedSpec {
    /// Configuration needed to deploy a dedicated environment index.
    pub fn new(environment: String) -> DedicatedSpec {
        DedicatedSpec { environment }
    }
}
