/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// DeleteRequest : The request for the `delete` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteRequest {
    /// Vectors to delete.
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
    /// This indicates that all vectors in the index namespace should be deleted.
    #[serde(rename = "deleteAll", skip_serializing_if = "Option::is_none")]
    pub delete_all: Option<bool>,
    /// The namespace to delete vectors from, if applicable.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// If specified, the metadata filter here will be used to select the vectors to delete. This is mutually exclusive with specifying ids to delete in the ids param or using delete_all=True. See [Understanding metadata](https://docs.pinecone.io/guides/data/understanding-metadata). Serverless indexes do not support delete by metadata. Instead, you can use the `list` operation to fetch the vector IDs based on their common ID prefix and then delete the records by ID.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
}

impl DeleteRequest {
    /// The request for the `delete` operation.
    pub fn new() -> DeleteRequest {
        DeleteRequest {
            ids: None,
            delete_all: None,
            namespace: None,
            filter: None,
        }
    }
}
