/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// DescribeIndexStatsRequest : The request for the `describe_index_stats` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DescribeIndexStatsRequest {
    /// If this parameter is present, the operation only returns statistics for vectors that satisfy the filter. See [Understanding metadata](https://docs.pinecone.io/guides/data/understanding-metadata).  Serverless indexes do not support filtering `describe_index_stats` by metadata.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
}

impl DescribeIndexStatsRequest {
    /// The request for the `describe_index_stats` operation.
    pub fn new() -> DescribeIndexStatsRequest {
        DescribeIndexStatsRequest { filter: None }
    }
}
