/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// FetchResponse : The response for the `fetch` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FetchResponse {
    #[serde(rename = "vectors", skip_serializing_if = "Option::is_none")]
    pub vectors: Option<std::collections::HashMap<String, models::Vector>>,
    /// The namespace of the vectors.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<models::Usage>>,
}

impl FetchResponse {
    /// The response for the `fetch` operation.
    pub fn new() -> FetchResponse {
        FetchResponse {
            vectors: None,
            namespace: None,
            usage: None,
        }
    }
}

