/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// Hit : A record whose vector values are similar to the provided search query.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Hit {
    /// The record id of the search hit.
    #[serde(rename = "_id")]
    pub _id: String,
    /// The similarity score of the returned record.
    #[serde(rename = "_score")]
    pub _score: f32,
    /// The selected record fields associated with the search hit.
    #[serde(rename = "fields")]
    pub fields: serde_json::Value,
}

impl Hit {
    /// A record whose vector values are similar to the provided search query.
    pub fn new(_id: String, _score: f32, fields: serde_json::Value) -> Hit {
        Hit {
            _id,
            _score,
            fields,
        }
    }
}

