/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// ImportErrorMode : Indicates how to respond to errors during the import process.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportErrorMode {
    /// Indicates how to respond to errors during the import process.
    #[serde(rename = "onError", skip_serializing_if = "Option::is_none")]
    pub on_error: Option<OnError>,
}

impl ImportErrorMode {
    /// Indicates how to respond to errors during the import process.
    pub fn new() -> ImportErrorMode {
        ImportErrorMode { on_error: None }
    }
}
/// Indicates how to respond to errors during the import process.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnError {
    #[serde(rename = "abort")]
    Abort,
    #[serde(rename = "continue")]
    Continue,
}

impl Default for OnError {
    fn default() -> OnError {
        Self::Abort
    }
}
