/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// IndexDescription : The response for the `describe_index_stats` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexDescription {
    /// A mapping for each namespace in the index from the namespace name to a summary of its contents. If a metadata filter expression is present, the summary will reflect only vectors matching that expression.
    #[serde(rename = "namespaces", skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<std::collections::HashMap<String, models::NamespaceSummary>>,
    /// The dimension of the indexed vectors. Not specified if `sparse` index.
    #[serde(rename = "dimension", skip_serializing_if = "Option::is_none")]
    pub dimension: Option<i64>,
    /// The fullness of the index, regardless of whether a metadata filter expression was passed. The granularity of this metric is 10%.  Serverless indexes scale automatically as needed, so index fullness  is relevant only for pod-based indexes.  The index fullness result may be inaccurate during pod resizing; to get the status of a pod resizing process, use [`describe_index`](https://docs.pinecone.io/reference/api/2024-10/control-plane/describe_index).
    #[serde(rename = "indexFullness", skip_serializing_if = "Option::is_none")]
    pub index_fullness: Option<f32>,
    /// The total number of vectors in the index, regardless of whether a metadata filter expression was passed
    #[serde(rename = "totalVectorCount", skip_serializing_if = "Option::is_none")]
    pub total_vector_count: Option<i64>,
    /// The metric used to measure similarity.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    /// The type of vectors stored in the index.
    #[serde(rename = "vectorType", skip_serializing_if = "Option::is_none")]
    pub vector_type: Option<String>,
}

impl IndexDescription {
    /// The response for the `describe_index_stats` operation.
    pub fn new() -> IndexDescription {
        IndexDescription {
            namespaces: None,
            dimension: None,
            index_fullness: None,
            total_vector_count: None,
            metric: None,
            vector_type: None,
        }
    }
}

