/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexModelSpec {
    #[serde(rename = "pod", skip_serializing_if = "Option::is_none")]
    pub pod: Option<Box<models::PodSpec>>,
    #[serde(rename = "serverless", skip_serializing_if = "Option::is_none")]
    pub serverless: Option<Box<models::ServerlessSpec>>,
}

impl IndexModelSpec {
    pub fn new() -> IndexModelSpec {
        IndexModelSpec {
            pod: None,
            serverless: None,
        }
    }
}
