/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// IndexList : The list of indexes that exist in the project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexList {
    #[serde(rename = "indexes", skip_serializing_if = "Option::is_none")]
    pub indexes: Option<Vec<models::IndexModel>>,
}

impl IndexList {
    /// The list of indexes that exist in the project.
    pub fn new() -> IndexList {
        IndexList {
            indexes: None,
        }
    }
}

