/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// ListResponse : The response for the `list` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListResponse {
    #[serde(rename = "vectors", skip_serializing_if = "Option::is_none")]
    pub vectors: Option<Vec<models::ListItem>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::Pagination>>,
    /// The namespace of the vectors.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<models::Usage>>,
}

impl ListResponse {
    /// The response for the `list` operation.
    pub fn new() -> ListResponse {
        ListResponse {
            vectors: None,
            pagination: None,
            namespace: None,
            usage: None,
        }
    }
}
