/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// ListImportsResponse : The response for the `list_imports` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListImportsResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::ImportModel>>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::Pagination>>,
}

impl ListImportsResponse {
    /// The response for the `list_imports` operation.
    pub fn new() -> ListImportsResponse {
        ListImportsResponse {
            data: None,
            pagination: None,
        }
    }
}
