/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// ModelIndexEmbed : The embedding model and document fields mapped to embedding inputs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelIndexEmbed {
    /// The name of the embedding model used to create the index.
    #[serde(rename = "model")]
    pub model: String,
    /// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If not specified, the metric will be defaulted according to the model. Cannot be updated once set.
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<Metric>,
    /// The dimensions of the vectors to be inserted in the index.
    #[serde(rename = "dimension", skip_serializing_if = "Option::is_none")]
    pub dimension: Option<i32>,
    /// The index vector type. You can use 'dense' or 'sparse'. If 'dense', the vector dimension must be specified.  If 'sparse', the vector dimension should not be specified.
    #[serde(rename = "vector_type", skip_serializing_if = "Option::is_none")]
    pub vector_type: Option<String>,
    /// Identifies the name of the text field from your document model that is embedded.
    #[serde(rename = "field_map", skip_serializing_if = "Option::is_none")]
    pub field_map: Option<serde_json::Value>,
    /// The read parameters for the embedding model.
    #[serde(rename = "read_parameters", skip_serializing_if = "Option::is_none")]
    pub read_parameters: Option<serde_json::Value>,
    /// The write parameters for the embedding model.
    #[serde(rename = "write_parameters", skip_serializing_if = "Option::is_none")]
    pub write_parameters: Option<serde_json::Value>,
}

impl ModelIndexEmbed {
    /// The embedding model and document fields mapped to embedding inputs.
    pub fn new(model: String) -> ModelIndexEmbed {
        ModelIndexEmbed {
            model,
            metric: None,
            dimension: None,
            vector_type: None,
            field_map: None,
            read_parameters: None,
            write_parameters: None,
        }
    }
}
/// The distance metric to be used for similarity search. You can use 'euclidean', 'cosine', or 'dotproduct'. If not specified, the metric will be defaulted according to the model. Cannot be updated once set.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Metric {
    #[serde(rename = "cosine")]
    Cosine,
    #[serde(rename = "euclidean")]
    Euclidean,
    #[serde(rename = "dotproduct")]
    Dotproduct,
}

impl Default for Metric {
    fn default() -> Metric {
        Self::Cosine
    }
}
