/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// NamespaceSummary : A summary of the contents of a namespace.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespaceSummary {
    /// The number of vectors stored in this namespace. Note that updates to this field may lag behind updates to the underlying index and corresponding query results, etc.
    #[serde(rename = "vectorCount", skip_serializing_if = "Option::is_none")]
    pub vector_count: Option<i64>,
}

impl NamespaceSummary {
    /// A summary of the contents of a namespace.
    pub fn new() -> NamespaceSummary {
        NamespaceSummary { vector_count: None }
    }
}
