/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// NamespaceDescription : A description of a namespace, including the name and record count.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamespaceDescription {
    /// The name of the namespace.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The total amount of records within the namespace.
    #[serde(rename = "record_count", skip_serializing_if = "Option::is_none")]
    pub record_count: Option<i64>,
}

impl NamespaceDescription {
    /// A description of a namespace, including the name and record count.
    pub fn new() -> NamespaceDescription {
        NamespaceDescription {
            name: None,
            record_count: None,
        }
    }
}
