/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: unstable
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// OperationModel : The OpeartionModel descriptions the status of an ongoing server operation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperationModel {
    #[serde(rename = "operation_id")]
    pub operation_id: String,
    /// The status of the operation
    #[serde(rename = "status")]
    pub status: Status,
    /// The progress made by the operation out of 100
    #[serde(rename = "percent_complete")]
    pub percent_complete: f32,
}

impl OperationModel {
    /// The OpeartionModel descriptions the status of an ongoing server operation
    pub fn new(operation_id: String, status: Status, percent_complete: f32) -> OperationModel {
        OperationModel {
            operation_id,
            status,
            percent_complete,
        }
    }
}
/// The status of the operation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "Cancelled")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

