/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// PaginationResponse : The pagination object that is returned with paginated responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationResponse {
    /// The token to use to retrieve the next page of results.
    #[serde(rename = "next")]
    pub next: String,
}

impl PaginationResponse {
    /// The pagination object that is returned with paginated responses.
    pub fn new(next: String) -> PaginationResponse {
        PaginationResponse { next }
    }
}
