/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: unstable
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// PodUpgradeTarget : The configuration for the target index. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PodUpgradeTarget {
    #[serde(rename = "serverless", skip_serializing_if = "Option::is_none")]
    pub serverless: Option<Box<models::UpgradeStarterRequestTargetServerless>>,
}

impl PodUpgradeTarget {
    /// The configuration for the target index. 
    pub fn new() -> PodUpgradeTarget {
        PodUpgradeTarget {
            serverless: None,
        }
    }
}

