/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// QueryRequest : The request for the `query` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryRequest {
    /// The namespace to query.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The number of results to return for each query.
    #[serde(rename = "topK")]
    pub top_k: i64,
    /// The filter to apply. You can use vector metadata to limit your search. See [Understanding metadata](https://docs.pinecone.io/guides/data/understanding-metadata). You can use vector metadata to limit your search. See [Understanding metadata](https://docs.pinecone.io/guides/data/understanding-metadata).
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    /// Indicates whether vector values are included in the response.
    #[serde(rename = "includeValues", skip_serializing_if = "Option::is_none")]
    pub include_values: Option<bool>,
    /// Indicates whether metadata is included in the response as well as the ids.
    #[serde(rename = "includeMetadata", skip_serializing_if = "Option::is_none")]
    pub include_metadata: Option<bool>,
    /// DEPRECATED. Use `vector` or `id` instead.
    #[serde(rename = "queries", skip_serializing_if = "Option::is_none")]
    pub queries: Option<Vec<models::QueryVector>>,
    /// The query vector. This should be the same length as the dimension of the index being queried. Each `query` request can contain only one of the parameters `id` or `vector`.
    #[serde(rename = "vector", skip_serializing_if = "Option::is_none")]
    pub vector: Option<Vec<f32>>,
    #[serde(rename = "sparseVector", skip_serializing_if = "Option::is_none")]
    pub sparse_vector: Option<Box<models::SparseValues>>,
    /// The unique ID of the vector to be used as a query vector. Each request  can contain either the `vector` or `id` parameter.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl QueryRequest {
    /// The request for the `query` operation.
    pub fn new(top_k: i64) -> QueryRequest {
        QueryRequest {
            namespace: None,
            top_k,
            filter: None,
            include_values: None,
            include_metadata: None,
            queries: None,
            vector: None,
            sparse_vector: None,
            id: None,
        }
    }
}
