/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// QueryResponse : The response for the `query` operation. These are the matches found for a particular query vector. The matches are ordered from most similar to least similar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryResponse {
    /// DEPRECATED. The results of each query. The order is the same as `QueryRequest.queries`.
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::SingleQueryResults>>,
    /// The matches for the vectors.
    #[serde(rename = "matches", skip_serializing_if = "Option::is_none")]
    pub matches: Option<Vec<models::ScoredVector>>,
    /// The namespace for the vectors.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<Box<models::Usage>>,
}

impl QueryResponse {
    /// The response for the `query` operation. These are the matches found for a particular query vector. The matches are ordered from most similar to least similar.
    pub fn new() -> QueryResponse {
        QueryResponse {
            results: None,
            matches: None,
            namespace: None,
            usage: None,
        }
    }
}
