/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// QueryVector : A single query vector within a `QueryRequest`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryVector {
    /// The query vector values. This should be the same length as the dimension of the index being queried.
    #[serde(rename = "values")]
    pub values: Vec<f32>,
    #[serde(rename = "sparseValues", skip_serializing_if = "Option::is_none")]
    pub sparse_values: Option<Box<models::SparseValues>>,
    /// An override for the number of results to return for this query vector.
    #[serde(rename = "topK", skip_serializing_if = "Option::is_none")]
    pub top_k: Option<i64>,
    /// An override the namespace to search.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// An override for the metadata filter to apply. This replaces the request-level filter.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
}

impl QueryVector {
    /// A single query vector within a `QueryRequest`.
    pub fn new(values: Vec<f32>) -> QueryVector {
        QueryVector {
            values,
            sparse_values: None,
            top_k: None,
            namespace: None,
            filter: None,
        }
    }
}
