/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// RestoreJobList : The list of restore jobs that exist in the project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestoreJobList {
    #[serde(rename = "data")]
    pub data: Vec<models::RestoreJobModel>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::PaginationResponse>>,
}

impl RestoreJobList {
    /// The list of restore jobs that exist in the project.
    pub fn new(data: Vec<models::RestoreJobModel>) -> RestoreJobList {
        RestoreJobList {
            data,
            pagination: None,
        }
    }
}

