/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// RestoreJobModel : The RestoreJobModel describes the status of a restore job.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestoreJobModel {
    /// Unique identifier for the restore job
    #[serde(rename = "restore_job_id")]
    pub restore_job_id: String,
    /// Backup used for the restore
    #[serde(rename = "backup_id")]
    pub backup_id: String,
    /// Name of the index into which data is being restored
    #[serde(rename = "target_index_name")]
    pub target_index_name: String,
    /// ID of the index
    #[serde(rename = "target_index_id")]
    pub target_index_id: String,
    /// Status of the restore job
    #[serde(rename = "status")]
    pub status: String,
    /// Timestamp when the restore job started
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp when the restore job finished
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    /// The progress made by the restore job out of 100
    #[serde(rename = "percent_complete", skip_serializing_if = "Option::is_none")]
    pub percent_complete: Option<f32>,
}

impl RestoreJobModel {
    /// The RestoreJobModel describes the status of a restore job.
    pub fn new(restore_job_id: String, backup_id: String, target_index_name: String, target_index_id: String, status: String, created_at: String) -> RestoreJobModel {
        RestoreJobModel {
            restore_job_id,
            backup_id,
            target_index_name,
            target_index_id,
            status,
            created_at,
            completed_at: None,
            percent_complete: None,
        }
    }
}

