/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScoredVector {
    /// This is the vector's unique id.
    #[serde(rename = "id")]
    pub id: String,
    /// This is a measure of similarity between this vector and the query vector.  The higher the score, the more they are similar.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// This is the vector data, if it is requested.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<f32>>,
    #[serde(rename = "sparseValues", skip_serializing_if = "Option::is_none")]
    pub sparse_values: Option<Box<models::SparseValues>>,
    /// This is the metadata, if it is requested.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl ScoredVector {
    pub fn new(id: String) -> ScoredVector {
        ScoredVector {
            id,
            score: None,
            values: None,
            sparse_values: None,
            metadata: None,
        }
    }
}

