/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchUsage {
    /// The number of read units consumed by this operation.
    #[serde(rename = "read_units")]
    pub read_units: i32,
    /// The number of embedding tokens consumed by this operation.
    #[serde(rename = "embed_total_tokens", skip_serializing_if = "Option::is_none")]
    pub embed_total_tokens: Option<i32>,
    /// The number of rerank units consumed by this operation.
    #[serde(rename = "rerank_units", skip_serializing_if = "Option::is_none")]
    pub rerank_units: Option<i32>,
}

impl SearchUsage {
    pub fn new(read_units: i32) -> SearchUsage {
        SearchUsage {
            read_units,
            embed_total_tokens: None,
            rerank_units: None,
        }
    }
}
