/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// SearchRecordsRequestQuery : .
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRecordsRequestQuery {
    /// The number of similar records to return.
    #[serde(rename = "top_k")]
    pub top_k: i32,
    /// The filter to apply. You can use vector metadata to limit your search. See [Understanding metadata](https://docs.pinecone.io/guides/data/understanding-metadata).
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<serde_json::Value>,
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<serde_json::Value>,
    #[serde(rename = "vector", skip_serializing_if = "Option::is_none")]
    pub vector: Option<Box<models::SearchRecordsVector>>,
    /// The unique ID of the vector to be used as a query vector.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl SearchRecordsRequestQuery {
    /// .
    pub fn new(top_k: i32) -> SearchRecordsRequestQuery {
        SearchRecordsRequestQuery {
            top_k,
            filter: None,
            inputs: None,
            vector: None,
            id: None,
        }
    }
}

