/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// SearchRecordsRequest : A search request for records in a specific namespace.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRecordsRequest {
    #[serde(rename = "query")]
    pub query: Box<models::SearchRecordsRequestQuery>,
    /// The fields to return in the search results. If not specified, the response will include all fields.
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
    #[serde(rename = "rerank", skip_serializing_if = "Option::is_none")]
    pub rerank: Option<Box<models::SearchRecordsRequestRerank>>,
}

impl SearchRecordsRequest {
    /// A search request for records in a specific namespace.
    pub fn new(query: models::SearchRecordsRequestQuery) -> SearchRecordsRequest {
        SearchRecordsRequest {
            query: Box::new(query),
            fields: None,
            rerank: None,
        }
    }
}

