/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// SearchRecordsRequestRerank : Parameters for reranking the initial search results.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRecordsRequestRerank {
    /// The name of the [reranking model](https://docs.pinecone.io/guides/inference/understanding-inference#reranking-models) to use.
    #[serde(rename = "model")]
    pub model: String,
    /// The field(s) to consider for reranking. If not provided, the default is `[\"text\"]`.  The number of fields supported is [model-specific](https://docs.pinecone.io/guides/inference/understanding-inference#reranking-models).
    #[serde(rename = "rank_fields")]
    pub rank_fields: Vec<String>,
    /// The number of top results to return after reranking. Defaults to top_k.
    #[serde(rename = "top_n", skip_serializing_if = "Option::is_none")]
    pub top_n: Option<i32>,
    /// Additional model-specific parameters. Refer to the [model guide](https://docs.pinecone.io/guides/inference/understanding-inference#reranking-models) for available model parameters.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The query to rerank documents against. If a specific rerank query is specified,  it overwrites the query input that was provided at the top level.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

impl SearchRecordsRequestRerank {
    /// Parameters for reranking the initial search results.
    pub fn new(model: String, rank_fields: Vec<String>) -> SearchRecordsRequestRerank {
        SearchRecordsRequestRerank {
            model,
            rank_fields,
            top_n: None,
            parameters: None,
            query: None,
        }
    }
}
