/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRecordsVector {
    /// This is the vector data included in the request.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<f32>>,
    /// The sparse embedding values.
    #[serde(rename = "sparse_values", skip_serializing_if = "Option::is_none")]
    pub sparse_values: Option<Vec<f32>>,
    /// The sparse embedding indices.
    #[serde(rename = "sparse_indices", skip_serializing_if = "Option::is_none")]
    pub sparse_indices: Option<Vec<i32>>,
}

impl SearchRecordsVector {
    pub fn new() -> SearchRecordsVector {
        SearchRecordsVector {
            values: None,
            sparse_values: None,
            sparse_indices: None,
        }
    }
}
