/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// SearchRecordsResponse : The records search response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRecordsResponse {
    #[serde(rename = "result")]
    pub result: Box<models::SearchRecordsResponseResult>,
    #[serde(rename = "usage")]
    pub usage: Box<models::SearchUsage>,
}

impl SearchRecordsResponse {
    /// The records search response.
    pub fn new(result: models::SearchRecordsResponseResult, usage: models::SearchUsage) -> SearchRecordsResponse {
        SearchRecordsResponse {
            result: Box::new(result),
            usage: Box::new(usage),
        }
    }
}

