/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// SparseValues : Vector sparse data. Represented as a list of indices and a list of  corresponded values, which must be with the same length.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SparseValues {
    /// The indices of the sparse data.
    #[serde(rename = "indices")]
    pub indices: Vec<i64>,
    /// The corresponding values of the sparse data, which must be with the same length as the indices.
    #[serde(rename = "values")]
    pub values: Vec<f32>,
}

impl SparseValues {
    /// Vector sparse data. Represented as a list of indices and a list of  corresponded values, which must be with the same length.
    pub fn new(indices: Vec<i64>, values: Vec<f32>) -> SparseValues {
        SparseValues { indices, values }
    }
}
