/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// StartImportResponse : The response for the `start_import` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartImportResponse {
    /// Unique identifier for the import operation.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl StartImportResponse {
    /// The response for the `start_import` operation.
    pub fn new() -> StartImportResponse {
        StartImportResponse { id: None }
    }
}
