/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// StartImportRequest : The request for the `start_import` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartImportRequest {
    /// The id of the [storage integration](https://docs.pinecone.io/guides/operations/integrations/manage-storage-integrations) that should be used to access the data.
    #[serde(rename = "integrationId", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    /// The [URI prefix](https://docs.pinecone.io/guides/data/understanding-imports#directory-structure) under which the data to import is available. All data within this prefix will be listed then imported into the target index. Currently only `s3://` URIs are supported.
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "errorMode", skip_serializing_if = "Option::is_none")]
    pub error_mode: Option<Box<models::ImportErrorMode>>,
}

impl StartImportRequest {
    /// The request for the `start_import` operation.
    pub fn new(uri: String) -> StartImportRequest {
        StartImportRequest {
            integration_id: None,
            uri,
            error_mode: None,
        }
    }
}
