/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// UpdateRequest : The request for the `update` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRequest {
    /// Vector's unique id.
    #[serde(rename = "id")]
    pub id: String,
    /// Vector data.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<f32>>,
    #[serde(rename = "sparseValues", skip_serializing_if = "Option::is_none")]
    pub sparse_values: Option<Box<models::SparseValues>>,
    /// Metadata to set for the vector.
    #[serde(rename = "setMetadata", skip_serializing_if = "Option::is_none")]
    pub set_metadata: Option<serde_json::Value>,
    /// The namespace containing the vector to update.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl UpdateRequest {
    /// The request for the `update` operation.
    pub fn new(id: String) -> UpdateRequest {
        UpdateRequest {
            id,
            values: None,
            sparse_values: None,
            set_metadata: None,
            namespace: None,
        }
    }
}

