/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: unstable
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpgradeStarterRequestTargetServerless {
    /// The public cloud where you would like your index hosted. Serverless indexes can be hosted only in AWS at this time.
    #[serde(rename = "cloud")]
    pub cloud: Cloud,
    /// The region where you would like your index to be created.  Serverless indexes can be created only in the us-east-1,us-west-2, and eu-west-1 regions of AWS at this time.
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "source_collection", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source_collection: Option<Option<serde_json::Value>>,
}

impl UpgradeStarterRequestTargetServerless {
    pub fn new(cloud: Cloud, region: String) -> UpgradeStarterRequestTargetServerless {
        UpgradeStarterRequestTargetServerless {
            cloud,
            region,
            source_collection: None,
        }
    }
}
/// The public cloud where you would like your index hosted. Serverless indexes can be hosted only in AWS at this time.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cloud {
    #[serde(rename = "gcp")]
    Gcp,
    #[serde(rename = "aws")]
    Aws,
    #[serde(rename = "azure")]
    Azure,
}

impl Default for Cloud {
    fn default() -> Cloud {
        Self::Gcp
    }
}

