/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: unstable
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// UpgradeStarterRequest : The configuration needed to upgrade an index.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpgradeStarterRequest {
    /// The name of the index. Resource name must be 1-45 characters long, start and end with an alphanumeric character, and consist only of lower case alphanumeric characters or '-'. 
    #[serde(rename = "index_name")]
    pub index_name: String,
    #[serde(rename = "target")]
    pub target: Box<models::UpgradeStarterRequestTarget>,
}

impl UpgradeStarterRequest {
    /// The configuration needed to upgrade an index.
    pub fn new(index_name: String, target: models::UpgradeStarterRequestTarget) -> UpgradeStarterRequest {
        UpgradeStarterRequest {
            index_name,
            target: Box::new(target),
        }
    }
}

