/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// UpsertRequest : The request for the `upsert` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertRequest {
    /// An array containing the vectors to upsert. Recommended batch limit is 100 vectors.
    #[serde(rename = "vectors")]
    pub vectors: Vec<models::Vector>,
    /// The namespace where you upsert vectors.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl UpsertRequest {
    /// The request for the `upsert` operation.
    pub fn new(vectors: Vec<models::Vector>) -> UpsertRequest {
        UpsertRequest {
            vectors,
            namespace: None,
        }
    }
}

