/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// UpsertResponse : The response for the `upsert` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertResponse {
    /// The number of vectors upserted.
    #[serde(rename = "upsertedCount", skip_serializing_if = "Option::is_none")]
    pub upserted_count: Option<i64>,
}

impl UpsertResponse {
    /// The response for the `upsert` operation.
    pub fn new() -> UpsertResponse {
        UpsertResponse {
            upserted_count: None,
        }
    }
}
