/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// UpsertRecord : The request for the `upsert` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertRecord {
    /// The unique ID of the record to upsert. Note that `id` can be used as an alias for `_id`.
    #[serde(rename = "_id")]
    pub _id: String,
}

impl UpsertRecord {
    /// The request for the `upsert` operation.
    pub fn new(_id: String) -> UpsertRecord {
        UpsertRecord {
            _id,
        }
    }
}

