/*
 * Pinecone Data Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2025-04
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vector {
    /// This is the vector's unique id.
    #[serde(rename = "id")]
    pub id: String,
    /// This is the vector data included in the request.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<f32>>,
    #[serde(rename = "sparseValues", skip_serializing_if = "Option::is_none")]
    pub sparse_values: Option<Box<models::SparseValues>>,
    /// This is the metadata included in the request.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl Vector {
    pub fn new(id: String) -> Vector {
        Vector {
            id,
            values: None,
            sparse_values: None,
            metadata: None,
        }
    }
}

