/*
 * Pinecone Control Plane API
 *
 * Pinecone is a vector database that makes it easy to search and retrieve billions of high-dimensional vectors.
 *
 * The version of the OpenAPI document: 2024-07
 * Contact: support@pinecone.io
 * Generated by: https://openapi-generator.tech
 */

use crate::openapi::models;
use serde::{Deserialize, Serialize};

/// EmbedRequest : Generate embeddings for inputs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbedRequest {
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::EmbedRequestParameters>>,
    #[serde(rename = "inputs")]
    pub inputs: Vec<models::EmbedRequestInputsInner>,
}

impl EmbedRequest {
    /// Generate embeddings for inputs
    pub fn new(model: String, inputs: Vec<models::EmbedRequestInputsInner>) -> EmbedRequest {
        EmbedRequest {
            model,
            parameters: None,
            inputs,
        }
    }
}

