name: CI

on:
    pull_request: {}
    push: {}
    workflow_dispatch: {}

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]
            rust: [stable]    
        steps:
        - uses: actions/checkout@v4
        - uses: hecrj/setup-rust-action@v2
          with:
            rust-version: ${{ matrix.rust }}
        - name: Build SDK
          run: cargo build
        - name: Build documentation
          run: cargo doc --no-deps
        - name: Run tests
          run: cargo test --verbose