name: CI

on:
    pull_request: {}
    push:
      branches:
        - main
    workflow_dispatch: {}

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]
            rust: [stable]    
        steps:
        - uses: actions/checkout@v4
        - uses: hecrj/setup-rust-action@v2
          with:
            rust-version: ${{ matrix.rust }}
        - name: Install protoc
          uses: arduino/setup-protoc@v3
        - name: Build SDK
          run: cargo build
        - name: Build documentation
          run: cargo doc --no-deps
        - name: Run tests
          env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          run: cargo test --verbose
